"""

kCGColorSpaceSRGB
kCGImageAlphaPremultipliedLast
kCGPathFillStroke
kCGRenderingIntentDefault

CFURLCreateFromFileSystemRepresentation
CGBitmapContextCreate
CGBitmapContextCreateImage
CGColorSpaceCreateDeviceRGB
CGColorSpaceCreateWithName
CGContextAddEllipseInRect
CGContextAddPath
CGContextAddRect
CGContextDrawImage
CGContextDrawPath
CGContextSetLineWidth
CGContextSetRGBFillColor
CGContextSetRGBStrokeColor
CGDataProviderCreateWithFilename
CGImageCreateWithJPEGDataProvider
CGImageCreateWithPNGDataProvider
CGImageDestinationAddImage
CGImageDestinationCreateWithURL
CGImageDestinationFinalize
CGImageGetHeight
CGImageGetWidth
CGPathAddLineToPoint
CGPathCreateMutable
CGPathMoveToPoint
CGRectMake

"""